spring.application.name=trainer-workload
spring.datasource.url=jdbc:h2:mem:workloaddb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081
# for testing
spring.h2.console.settings.web-allow-others=true
logging.level.com.gym.crm.trainerworkload=DEBUG
#ActiveMQ Configuration
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
activemq.queue.workload-update=trainer.workload.update.queue
activemq.queue.workload-dlq=trainer.workload.dlq.queue
# MongoDB Configuration
spring.mongodb.uri=mongodb://localhost:27017/gym
